### ISSUE TITLE
Support for more colors in gradients?

### ISSUE THREAD

**Issue by oliviathevampire** [ewanhowell5195/blockbenchPlugins#2]
Is there any chance there could be a way of adding more colors in gradients than just max 3 colors?

**Comment by ewanhowell5195** [comment]
max colours is now 5. if you want more, its not hard to just use an image editor
![image](https://github.com/ewanhowell5195/blockbenchPlugins/assets/48070995/82a18e55-baf1-45fb-9fc4-c3999335d71c)

**Comment by ewanhowell5195** [comment]
will be in next update
