### ISSUE TITLE
Icon for variants?

### ISSUE THREAD

**Issue by oliviathevampire** [ewanhowell5195/blockbenchPlugins#4]
One nice thing for be an icon for the textures that has variants

**Comment by ewanhowell5195** [comment]
i'll see what I can do

by the way can you add the line terminators to the planks that you made they are missing them, as well as possibly add the other plank types
![image](https://github.com/ewanhowell5195/blockbenchPlugins/assets/48070995/289a387b-13c9-49bd-8705-63289dec8b32)

**Comment by oliviathevampire** [comment]
Yep I am working on it!

**Comment by oliviathevampire** [comment]
Do you have a discord where I can add you btw? like if I have questions

**Comment by ewanhowell5195** [comment]
https://discord.ewanhowell.com/
