### ISSUE TITLE
[CEM Template Loader] Trident model has been changed in vanilla

### ISSUE THREAD

**Issue by GeForceLegend** [ewanhowell5195/blockbenchPlugins#6]
From unknown version, trident model in vanilla has been changed. According to test result, it looks like the "center rod" is splitted into 2 parts, the upper one is 4 pixels high and the lower one is 25 pixels high.

**Comment by GeForceLegend** [comment]
Looks like this change happens in 1.15.X. Below image is decompiled TridentModel.class without remapping in 1.15.2 and 1.14.4.
![20231005171300](https://github.com/ewanhowell5195/blockbenchPlugins/assets/41003546/e948d238-b81f-4aad-978e-382b139008a4)

**Comment by ewanhowell5195** [comment]
fixed
