### ISSUE TITLE
Suggesting EMF and ETF support.

### ISSUE THREAD

**Issue by Creatomat** [ewanhowell5195/blockbenchPlugins#7]
## I am suggesting [entity model features](https://modrinth.com/mod/entity-model-features) support for the cem template loader:  
**This would include some changes:**  
  
--> Removing the **player** and **slim player** model from the unsupported category.  
  
**Some additions:**  
  
--> Add an option for the plugin to allow exporting even with errors as emf and etf support custom variables through an api, it is currently impossible to use because of this.  
--> Add support for [emf only animation variables](https://github.com/Traben-0/Entity_Model_Features/blob/master/FEATURES.md#emf-only-animation-variables).  

**That's it really, even if u decide not to add this, thanks for reading, cool plugin man**

**Comment by Traben-0** [comment]
An option allowing unknown variables and methods to actually be exported would be a helpful setting on its own

The pack makers would be changing this setting at their own risk ofc

**Comment by ewanhowell5195** [comment]
https://www.blockbench.net/plugins/emf_animation_addon
